In [12]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

iris = load_iris()

print("데이터셋 샘플:")
print(iris.data[:5])

print("\n타깃 샘플:")
print(iris.target[:5]) 

print("\n특성(shape):", iris.data.shape)
print("타깃(shape):", iris.target.shape)

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)


model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("정확도 출력",accuracy)



데이터셋 샘플:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

타깃 샘플:
[0 0 0 0 0]

특성(shape): (150, 4)
타깃(shape): (150,)
정확도 출력 1.0
