In [7]:
pip install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
    --------------------------------------- 0.5/38.8 MB 2.1 MB/s eta 0:00:19
   - -------------------------------------- 1.0/38.8 MB 2.3 MB/s eta 0:00:17
   - -------------------------------------- 1.6/38.8 MB 2.3 MB/s eta 0:00:17
   -- ------------------------------------- 2.4/38.8 MB 2.7 MB/s eta 0:00:14
   --- ------------------------------------ 3.1/38.8 MB 3.0 MB/s eta 0:00:12
   --- ------------------------------------ 3.7/38.8 MB 3.1 MB/s eta 0:00:12
   ---- ----------------------------------- 4.5/38.8 MB 3.0 MB/s eta 0:00:12
   ---- ----------------------------------- 4.7/38.8 MB 2.8 MB/s eta 0:00:13
   ----- ---------------------------------- 5.5/38.8 MB 2.8 MB/s eta 0:00:12
   ------ --------------------------------- 6.6/38.8 MB 3.1 MB/s eta 0:00:11
   ------- -------------------------------- 7.6/38.8 MB 3.2 MB/s eta 0:00:10
   -------- ------------------------------- 8.4/38.8 MB 3.3 MB/s eta 0:00:10
   ---

In [11]:
pip install Sklearn.datasets

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement Sklearn.datasets (from versions: none)
ERROR: No matching distribution found for Sklearn.datasets


In [13]:
python --version

NameError: name 'python' is not defined

In [15]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [35]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()

print("데이터셋 샘플:")
print(iris.data[:5])

print("\n타깃 샘플:")
print(iris.target[:5]) 

print("\n특성(shape):", iris.data.shape)
print("타깃(shape):", iris.target.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score



데이터셋 샘플:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

타깃 샘플:
[0 0 0 0 0]

특성(shape): (150, 4)
타깃(shape): (150,)
